### ISSUE TITLE
Completed (and sometimes deleted) pods are still marked as "Running" and consume resources

### ISSUE THREAD

**Issue by jameschen1519** [apache/incubator-yunikorn-core#90] opened 2020-02-21 21:09 UTC
When running spark jobs via spark-submit on Kubernetes and applying the Yunikorn scheduler to a driver/executor pairing, upon termination the Yunikorn scheduler does not mark these jobs as complete, and the jobs are still marked as "Running". This takes up resources in the job queues to which the driver/executors are assigned, eventually resulting in resource starvation until the drivers are manually deleted. Unfortunately, deletion of these pods might not necessarily free up resources--too many cycles of starting and stopping Yunikorn-scheduled spark pods results in all resources being consumed, even when there are no more Yunikorn-scheduled spark pods available.

(It is also worth noting that the driver and executor jobs enter the same queue regardless of what the executor podTemplateFile specifies. We are unsure of if this is a feature or a bug.)

Listed below are the reproduction steps. Please let me know if any clarification is needed; thanks.

Environment setup:
For setting up the Yunikorn pods (Used the helm chart, but also tried setting it up manually):

`helm install ./yunikorn --namespace test ./yunikorn --generate-name`

queues.yaml snippet to be put into yunikorn:
`kubectl -n test edit configmap yunikorn-scheduler`
```
  queues.yaml: |
    partitions:
      - name: default
        placementrules:
          - name: provided
            create: false
        queues:
          - name: root
            submitacl: '*'
            queues:
              - name: driver
                resources:
                  guaranteed:
                    memory: 10000
                    vcore: 1000
                  max:
                    memory: 40000
                    vcore: 9000
              - name: executors
                resources:
                  guaranteed:
                    memory: 1000
                    vcore: 1000
                  max:
                    memory: 15000
                    vcore: 6000

```

Command used:

```
spark-submit     \
--master k8s://https://<YOUR K8S IP>:6443     \
--deploy-mode cluster     \
--name spark-pi     \
--class org.apache.spark.examples.SparkPi     \
--conf spark.kubernetes.container.image=<YOUR SPARK IMAGE>     \
--conf spark.kubernetes.namespace=test     \
--conf spark.driver.extraClassPath=/opt/hadoop/etc/hadoop     \
--conf spark.ssl.enabled=false     \
--conf spark.authenticate=false     \
--conf spark.kubernetes.driver.podTemplateFile=/driver.yaml \
--conf spark.kubernetes.executor.podTemplateFile=/executor.yaml \
--conf spark.network.crypto.enabled=false \
<YOUR SPARK JAR FILE; E.G. hdfs://<YOUR HDFS URL>/sparkexample.jar> &
```

Under driver.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    spark-app-id: spark-00001
    queue: root.driver
spec:
  schedulerName: yunikorn

```

Under executor.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    spark-app-id: spark-00001
    queue: root.executors
spec:
  schedulerName: yunikorn
```

An image showing the buggy memory usage (Both drivers are in a complete state but are still considered running and take up resources):

![sparkrunningdriver](https://user-images.githubusercontent.com/57380512/75072139-b28dce00-54ab-11ea-8ed9-338e364add1f.png)

**Comment by yangwwei** [comment] 2020-02-21 23:20
Hi @jameschen1519 

This is a kind of known issue for me, we are also hitting this internally while running Spark.
For job completion, we added a completion handler in https://github.com/apache/incubator-yunikorn-k8shim/blob/fc2b3a5452acbfdea536c120fa755788baaa15fc/pkg/cache/application.go#L348, that is supposed to transit Spark job to complete after the driver completes. Somehow that is not triggered. I will look into this.

> It is also worth noting that the driver and executor jobs enter the same queue regardless of what the executor podTemplateFile specifies. We are unsure if this is a feature or a bug.
this is by design, for each job, we enforce all tasks are belonging to one same queue

**Comment by yangwwei** [comment] 2020-02-22 01:43
I think the issue here is, when a Spark job completes, the Spark driver pod is left there like:

```
NAME                            READY   STATUS      RESTARTS   AGE
spark-pi-1582333424486-driver   0/1     Completed   0          15m
```

if the pod exists, we cannot release the resource for it. our release logic is triggered when a pod is deleted from K8s. The question becomes: who should clean up Spark driver pods? 
A not so bad idea would be, some people are doing this, run a cron-job do GC for completed Spark drivers, that can help to release the resources.

@jameschen1519  what do you think?

**Comment by jameschen1519** [comment] 2020-02-24 19:21
Setting up a cron-job would be a viable temporary workaround for us, but logically, we think that it might be best for the issue to be fixed regardless. The completed pods are not using any resources (and will never consume any actual resources ever again), so they shouldn't be marked as using memory.

I haven't looked through the release logic in the code yet, but would it be possible to listen for pod completion as well as deletion?

**Comment by yangwwei** [comment] 2020-02-24 19:46
Hi @jameschen1519 

Look at the definition of pod phases: 

- Pending
- Running
- Succeeded
- Failed
- unknown

for `Succeed` and `Failed`, once pod reaches such state, it means all containers are terminated, and I think this also means they will not get any other chance to run again[1]. In this case, we should be good to release resources. Note, assumption [1] must be true otherwise it will cause some issues.

**Comment by jameschen1519** [comment] 2020-02-24 21:18
I think [1] should be true, unless there's some sort of misdirection in the documentation: under https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/, it suggests that Succeeded jobs will not be restarted, and while it doesn't include that line under the Failed state, usually restarts redirect the pod state into the CrashLoopBackOff state.

**Comment by yangwwei** [comment] 2020-02-25 21:39
Make sense. working on a fix for this now.

**Comment by yangwwei** [comment] 2020-02-26 23:08
FYI: this one is blocked by https://github.com/apache/incubator-yunikorn-k8shim/pull/72. Once that is merged, I should be able to provide a PR for this one.

**Comment by yangwwei** [comment] 2020-03-02 23:31
PR opened: https://github.com/apache/incubator-yunikorn-k8shim/pull/80

**Comment by wilfred-s** [comment] 2020-03-04 03:10
Moved this issue to JIRA, updates and tracking should be managed from JIRA:
https://issues.apache.org/jira/browse/YUNIKORN-11

**Closed by wilfred-s** 2020-03-04 03:10 UTC
